//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RayanSport.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source= 169.254.92.252;Initial Catalog=rayan_sport;User id=test;Password=Hos" +
            "einNima1234;")]
        public string rayan_sportConnectionString {
            get {
                return ((string)(this["rayan_sportConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 196, 0")]
        public global::System.Drawing.Color DarkYellow {
            get {
                return ((global::System.Drawing.Color)(this["DarkYellow"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 215, 64")]
        public global::System.Drawing.Color MediumYellow {
            get {
                return ((global::System.Drawing.Color)(this["MediumYellow"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 238, 88")]
        public global::System.Drawing.Color LightYellow {
            get {
                return ((global::System.Drawing.Color)(this["LightYellow"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("38, 50, 56")]
        public global::System.Drawing.Color VeryDarkBlueGrey {
            get {
                return ((global::System.Drawing.Color)(this["VeryDarkBlueGrey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("55, 71, 79")]
        public global::System.Drawing.Color DarkBlueGrey {
            get {
                return ((global::System.Drawing.Color)(this["DarkBlueGrey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("120, 144, 156")]
        public global::System.Drawing.Color MediumBlueGrey {
            get {
                return ((global::System.Drawing.Color)(this["MediumBlueGrey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("207, 216, 220")]
        public global::System.Drawing.Color LightBlueGrey {
            get {
                return ((global::System.Drawing.Color)(this["LightBlueGrey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250, 250, 250")]
        public global::System.Drawing.Color LightGrey {
            get {
                return ((global::System.Drawing.Color)(this["LightGrey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("224, 224, 224")]
        public global::System.Drawing.Color MediumGrey {
            get {
                return ((global::System.Drawing.Color)(this["MediumGrey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("158, 158, 158")]
        public global::System.Drawing.Color DarkGrey {
            get {
                return ((global::System.Drawing.Color)(this["DarkGrey"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("41, 182, 246")]
        public global::System.Drawing.Color Blue {
            get {
                return ((global::System.Drawing.Color)(this["Blue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("76, 175, 80")]
        public global::System.Drawing.Color Green {
            get {
                return ((global::System.Drawing.Color)(this["Green"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("126, 87, 194")]
        public global::System.Drawing.Color Purple {
            get {
                return ((global::System.Drawing.Color)(this["Purple"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("244, 67, 54")]
        public global::System.Drawing.Color Red {
            get {
                return ((global::System.Drawing.Color)(this["Red"]));
            }
        }
    }
}
